### ISSUE TITLE
No MacOS support

### ISSUE THREAD

**Issue by the-brute-force** [mdegirolami/sing#4]
I just found this and tried to use on on my Mac, but there's no build available for MacOS

Would it be possible to get a Mac version available?

If need be, I could help compile it on my Mac

**Comment by mdegirolami** [comment]
Hi Harry,

I had in my plans to add osx to the list of supported operating systems but
not just now. (I'm too busy with the core features).
If you could help compile the code on mac that would be just great !!
I suppose you could start installing ninja, vsc and compiling the compiler.
There should be modifications to the build files but not to the sources
(may be some minor changes).
When you will step into the library then you may need to rewrite some code
even if the linux version should work pretty well in many cases. (look at
_WIN32 macros to detect the platform dependent portions).
Let me know if you need any help.

Bye

Maurizio




<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by the-brute-force** [comment]
I've been looking into the compiler and I'd love clarification on a few parts.

First off, where is the default Sing search location?
I've looked around and there doesn't appear to be an obvious definition

Secondly, the compiler may need multiple adjustments to make it work as well
Clang doesn't want to play nice with the code and the libraries' locations need to be redefined

**Comment by mdegirolami** [comment]
I suppose you already followed the[ getting started guide](https://mdegirolami.wixsite.com/singlang/copy-of-interfacing-sing-and-c-2) and installed sing on a supported platform. I think this is an important step to familiarise with the build environment.
The sing compiler has no default search path: if you take a look at the ninja files you can see the sdk path is always added explicitly in the command line. 
In build_aux.ninja the sing compiler is invoked by the sc rule. The included directories are: "-I $sing -I $singhh" which map to ../../sing (the compiler is run into build/obj_x) and to the sdk sing includes. 
The sdk itself is contained inside the vsc plugin. (typically at ~/.vscode/extensions/mauriziodegirolami.vscode-sing-0.41.0/sdk).

If you find clang is not happy with the code generated by the sing compiler please send me an example with the rejected code and the error codes. 
If you want to try to fix the compiler yourself, the cpp_synth.* files are the right place to look at. For each node in the ast tree you find there the routine who generates the code.

**Comment by the-brute-force** [comment]
I did follow the guide on a Linux virtual machine and that's why I was wondering.
I looked throughout the code and didn't find a location and that's what I thought

Right now I'm using Alpine Linux with the packages `clang ninja musl-dev` installed
Pretty much all the only error on Linux is due to GCC specific header `unordered_map`

On MacOS, it has some weird platform-specific errors
```
clang: warning: argument unused during compilation: '-s' [-Wunused-command-line-argument]
In file included from ../../src/ast_checks.cpp:4:
In file included from ../../src/ast_checks.h:7:
../../src/symbols_storage.h:13:20: error: implicit instantiation of undefined template 'std::hash<std::basic_string<char>>'
            return(std::hash<std::string>{}(str.c_str()));
                   ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__memory/shared_ptr.h:1710:50: note: template is declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS hash;
                                                 ^
In file included from ../../src/ast_checks.cpp:4:
In file included from ../../src/ast_checks.h:7:
../../src/symbols_storage.h:13:44: error: implicit instantiation of undefined template 'std::hash<std::basic_string<char>>'
            return(std::hash<std::string>{}(str.c_str()));
                                           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__memory/shared_ptr.h:1710:50: note: template is declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS hash;
                                                 ^
../../src/ast_checks.cpp:1024:13: warning: 15 enumeration values not handled in switch: 'ANT_FILE', 'ANT_DEPENDENCY', 'ANT_TYPE'... [-Wswitch]
    switch (nodetype) {
            ^
../../src/ast_checks.cpp:1024:13: note: add missing switch cases
    switch (nodetype) {
            ^
../../src/ast_checks.cpp:1102:21: warning: 104 enumeration values not handled in switch: 'TOKEN_COMMENT', 'TOKEN_INLINE_COMMENT', 'TOKEN_NAME'... [-Wswitch]
            switch (node->operation_) {
                    ^
../../src/ast_checks.cpp:1102:21: note: add missing switch cases
            switch (node->operation_) {
                    ^
../../src/ast_checks.cpp:1484:13: warning: 27 enumeration values not handled in switch: 'ANT_FILE', 'ANT_DEPENDENCY', 'ANT_VAR'... [-Wswitch]
    switch (node->GetType()) {
            ^
../../src/ast_checks.cpp:1484:13: note: add missing switch cases
    switch (node->GetType()) {
            ^
../../src/ast_checks.cpp:1983:13: warning: 27 enumeration values not handled in switch: 'ANT_FILE', 'ANT_DEPENDENCY', 'ANT_VAR'... [-Wswitch]
    switch (node->GetType()) {
            ^
../../src/ast_checks.cpp:1983:13: note: add missing switch cases
    switch (node->GetType()) {
            ^
../../src/ast_checks.cpp:2661:13: warning: 27 enumeration values not handled in switch: 'ANT_FILE', 'ANT_DEPENDENCY', 'ANT_VAR'... [-Wswitch]
    switch (node->GetType()) {
            ^
../../src/ast_checks.cpp:2661:13: note: add missing switch cases
    switch (node->GetType()) {
            ^
5 warnings and 2 errors generated.
```

**Comment by mdegirolami** [comment]
For the first problem, this function should replace the current one at the beginning of symbols_storage.h:

namespace std {
    template<> struct hash<SingNames::string>
    {
        typedef std::size_t result_type;
        result_type operator()(SingNames::string const& str) const noexcept
        {
            std::hash<std::string> stdhash;
            return(stdhash(str.c_str()));
        }
    };
}

clang doesn't like to create a temporary unnamed std::hash<std::string> on the fly.

The warnings can be solved adding a default to the switch. The default action could be an assertion because other cases should never happen.

There is another point I want to signal:  I made the compiler dependent on the singlib library because I needed some functions, then I made the library dependent on the compiler, because I wanted to use sing for a part of the library. 
This was pretty stupid because now none of them can be compiled on a new platform !! Please procede as follow:
- In build_aux.json of the library delete json.o from the $lib_target dependencies (row 48) and compile the library.
- compile the compiler
- restore build_aux.json and compile the library again.

**Comment by the-brute-force** [comment]
I'll test this when I'm able to, I'll also see about decoupling the library and the compiler

**Comment by the-brute-force** [comment]
So now that I'm done with finals, I can finally work on this

I've installed so many packages that my tools are fighting with each other so I'll see about setting up a clean environment I can use

The major issue is Xcode when building and requesting headers that I don't have
```
[1/24] c++ -std=c++11 -MD -MF target.o...g  -c ../../src/target.cpp -o target.o
2022-05-21 14:49:27.964 xcodebuild[22718:3351708] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
```

**Comment by the-brute-force** [comment]
So I've done some work and while compiling, I've got some new issues

```
sio.cpp:1255:81: error: ordered comparison between pointer and zero ('int64_t *' (aka 'long long *') and 'int')
        if (parseUnsignedHex((uint64_t*)value, from, at + 2, last_pos) && value >= 0) {
                                                                          ~~~~~ ^  ~
sio.cpp:1344:19: warning: result of comparison of constant 224 with expression of type 'char' is always false [-Wtautological-constant-out-of-range-compare]
    while (buf[0] == 0xe0) {
           ~~~~~~ ^  ~~~~
1 warning and 1 error generated.
```

**Comment by the-brute-force** [comment]
```
str.cpp:349:68: warning: if statement has empty body [-Wempty-body]
    if (compareAt(str->c_str(), 0, prefix, &end, insensitive) == 0); {
                                                                   ^
str.cpp:349:68: note: put the semicolon on a separate line to silence this warning
1 warning generated.
```

```
sys.cpp:646:19: error: use of undeclared identifier 'CLOCK_BOOTTIME'; did you mean '_CLOCK_REALTIME'?
    clock_gettime(CLOCK_BOOTTIME, &ts);
                  ^~~~~~~~~~~~~~
                  _CLOCK_REALTIME
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/time.h:154:1: note: '_CLOCK_REALTIME' declared here
_CLOCK_REALTIME __CLOCK_AVAILABILITY = 0,
^
1 error generated.
```

**Comment by the-brute-force** [comment]
Did a temporary patch and I'll see what happens
`if (parseUnsignedHex((uint64_t*)value, from, at + 2, last_pos) && value != NULL) {`

**Comment by mdegirolami** [comment]
Hi Harry, thanks for spotting all these subtle bugs. (and sorry for the inconvenience).
A few fix for you. Tomorrow I will take a look at the other details. 

~~~
if (parseUnsignedHex((uint64_t*)value, from, at + 2, last_pos) && value >= 0) {
~~~
the intended meaning was:
~~~
if (parseUnsignedHex((uint64_t*)value, from, at + 2, last_pos) && *value >= 0) {
~~~
meaning that if the unsigned int is too big to fit a int64_t the *value is negative and the function fails even if parseUnsignedHex didn't.

The new kbdGet() is:
~~~
std::string kbdGet()
{
    char buf[2];
    int value = _getch();
    while (value == 0xe0 || value == 0) {
        _getch();               // second part of control char / arrow.
        value = _getch();
    }
    buf[0] = value;
    buf[1] = 0;
    return(std::string(buf));
}
~~~
The while is meant to discard function keys and arrows, which have not an ascii value.

**Comment by the-brute-force** [comment]
No problem, I'll try out the patches in a bit. Also I think that a way to make it easier to port to new platforms is to have the Sing libraries already turned into headers using the compiler.

**Comment by mdegirolami** [comment]
~~~
    if (compareAt(str->c_str(), 0, prefix, &end, insensitive) == 0); {
~~~
The ";" needs to be erased. Interestingly this is not strictly a bug, because by default compareAt returns and 'end' value which fits the erase function in all cases.

comparing this:
[https://linux.die.net/man/2/clock_gettime](https://linux.die.net/man/2/clock_gettime)
with this:
[https://opensource.apple.com/source/Libc/Libc-1158.1.2/gen/clock_gettime.3.auto.html](https://opensource.apple.com/source/Libc/Libc-1158.1.2/gen/clock_gettime.3.auto.html)
I suppose the equivalent of CLOCK_BOOTTIME for osx is CLOCK_UPTIME_RAW.
You will need conditional compilation to change this only on mac:
~~~
#ifdef OSX
        clock_gettime(CLOCK_UPTIME_RAW, &ts);
#else
        clock_gettime(CLOCK_BOOTTIME, &ts);
#endif
~~~

Sing libraries turned into headers ? Do you mean the sing files in singlib/sing_headers converted to singlib/inc ?

**Comment by the-brute-force** [comment]
I was talking about the singlib/sing_headers used in singlib/src_lib

Also could you add `#include <string>` in compiler/src/symbols_storage.h, the compiler always complains and every time I clone the repo I need to do it

**Comment by the-brute-force** [comment]
Also I manually compiled the headers days ago, but I got a working version of Sing on MacOS natively just now

<img width="404" alt="Screen Shot 2022-05-27 at 22 33 08" src="https://user-images.githubusercontent.com/94585779/170808290-e4e2ab73-0c4a-4d69-836e-3f699c485902.png">

**Comment by the-brute-force** [comment]
I'm going to compile Sing on another machine so it won't be influenced by my developer tools and upload the binaries

**Comment by the-brute-force** [comment]
After fixing some definitions, I compiled it successfully

Going to upload the binaries when I get wifi again

**Comment by the-brute-force** [comment]
Since there's now MacOS support, I'll close this
